services:
  scrap:
    build:
      context: .
      dockerfile: ./docker/selenium/Dockerfile
    env_file: .env
    volumes:
      - ./hhscrapper:/hhscrapper
      - ./manage.py:/manage.py
      - ./resume.txt:/resume.txt
      - ./resume.sample.txt:/resume.sample.txt
      - ./prompt.txt:/prompt.txt
      - ./prompt.sample.txt:/prompt.sample.txt
      - ./saved_cookies:/saved_cookies
      - ./latest_logs:/latest_logs
      - ./downloaded_files:/downloaded_files
