# Generated by Django 6.0.4 on 2026-04-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_id', models.IntegerField()),
                ('url', models.URLField()),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('salary', models.TextField(blank=True, null=True)),
                ('compensation', models.TextField(blank=True, null=True)),
                ('work_experience', models.TextField(blank=True, null=True)),
                ('common_employment', models.TextField(blank=True, null=True)),
                ('hiring_format', models.TextField(blank=True, null=True)),
                ('work_schedule', models.TextField(blank=True, null=True)),
                ('work_hours', models.TextField(blank=True, null=True)),
                ('work_format', models.TextField(blank=True, null=True)),
                ('skills', models.ManyToManyField(related_name='skills', to='app.skill')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='vacancies',
            field=models.ManyToManyField(related_name='vacancies', to='app.vacancy'),
        ),
    ]
