# Generated by Django 6.0.4 on 2026-04-09 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_skill_vacancies_alter_vacancy_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='consensus',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='koef',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='load_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='start_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='hh_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.CreateModel(
            name='LLMResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm', models.IntegerField(choices=[(1, 'llama3.1'), (2, 'deepseek-r1:14b'), (3, 'gemma3:12b'), (4, 'qwen3:14b'), (5, 'phi4:14b')])),
                ('corresponds', models.BooleanField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('extra', models.TextField(blank=True, null=True)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_results', to='app.vacancy')),
            ],
            options={
                'verbose_name': 'LLM Result',
                'verbose_name_plural': 'LLM Results',
            },
        ),
    ]
