# Generated by Django 6.0.4 on 2026-04-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_vacancy_consensus_vacancy_koef_vacancy_load_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
