# Generated by Django 6.0.4 on 2026-04-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_skill_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='koef',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='notified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
