# Generated by Django 6.0.4 on 2026-05-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_vacancy_koef_alter_vacancy_notified'),
    ]

    operations = [
        migrations.RunSQL('TRUNCATE app_LLMResult'),
    ]
