# Generated by Django 6.0.4 on 2026-05-21 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20260521_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecuteLLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('llm', models.IntegerField(choices=[(1, 'llama3.1'), (2, 'deepseek-r1:14b'), (3, 'gemma3:12b'), (4, 'qwen3:14b'), (5, 'phi4:14b')], unique=True)),
            ],
            options={
                'verbose_name': 'Execute LLM',
                'verbose_name_plural': 'Execute LLMs',
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('sys_template', models.TextField(blank=True, null=True)),
                ('human_template', models.TextField(blank=True, help_text='You may use template tags for rendering.Available tags are {{TITLE}} {{WORK_EXP}} {{DESC}} {{SKILLS}}', null=True, verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(blank=True, null=True, verbose_name='HHQuery')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Title')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Search Query',
                'verbose_name_plural': 'Search Queries',
            },
        ),
        migrations.RemoveField(
            model_name='llmresult',
            name='vacancy',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='consensus',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='koef',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='notified',
        ),
        migrations.CreateModel(
            name='SearchQueryPromptLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llms', models.ManyToManyField(related_name='+', to='app.executellm')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_links', to='app.prompt')),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_links', to='app.searchquery')),
            ],
            options={
                'verbose_name': 'Search Query Prompt Link',
                'verbose_name_plural': 'Search Query Prompt Links',
            },
        ),
        migrations.AddField(
            model_name='searchquery',
            name='prompts',
            field=models.ManyToManyField(related_name='search_queries', through='app.SearchQueryPromptLink', to='app.prompt', verbose_name='Prompts'),
        ),
        migrations.CreateModel(
            name='VacancyPromptDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consensus', models.BooleanField(blank=True, null=True)),
                ('koef', models.FloatField(blank=True, db_index=True, null=True)),
                ('notified', models.BooleanField(db_index=True, default=False)),
                ('query_prompt_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.searchquerypromptlink')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vacancy')),
            ],
            options={
                'verbose_name': 'Vacancy Prompt Decision',
                'verbose_name_plural': 'Vacancy Prompt Decisions',
            },
        ),
        migrations.AddField(
            model_name='llmresult',
            name='vacancy_prompt_decision',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='llm_results', to='app.vacancypromptdecision'),
            preserve_default=False,
        ),
    ]
