# Generated by Django 6.0.4 on 2026-05-25 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_executellm_prompt_searchquery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmresult',
            name='execution_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancypromptdecision',
            name='prompt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.prompt'),
        ),
        migrations.AddConstraint(
            model_name='vacancypromptdecision',
            constraint=models.UniqueConstraint(fields=('vacancy', 'prompt'), name='unique_vacancy_prompt_decision'),
        ),
    ]
