# Generated by Django 6.0.4 on 2026-05-25 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_llmresult_execution_done_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmresult',
            name='vacancy_prompt_decision',
        ),
        migrations.AddField(
            model_name='llmresult',
            name='prompt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_results', to='app.prompt'),
        ),
    ]
