# Generated by Django 6.0.4 on 2026-05-25 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_vacancypromptdecision_llm_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmresult',
            name='vacancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_results', to='app.vacancy'),
        ),
        migrations.AddField(
            model_name='vacancypromptdecision',
            name='state',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Ready to Execute'), (3, 'ALL_TASKS_EXECUTED'), (4, 'Done')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='vacancypromptdecision',
            name='consensus',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
