# Generated by Django 6.0.4 on 2026-05-25 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_llmresult_vacancy_vacancypromptdecision_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancypromptdecision',
            name='query_prompt_link',
        ),
    ]
