# Generated by Django 6.0.4 on 2026-05-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_vacancypromptdecision_query_prompt_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
            ],
            options={
                'verbose_name': 'Stop Word',
                'verbose_name_plural': 'Stop Words',
            },
        ),
        migrations.AddField(
            model_name='prompt',
            name='stop_words',
            field=models.ManyToManyField(related_name='prompts', to='app.stopword'),
        ),
    ]
