# Generated by Django 6.0.4 on 2026-05-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_stopword_prompt_stop_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancypromptdecision',
            name='state',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Ready to Execute'), (3, 'ALL_TASKS_EXECUTED'), (4, 'Done'), (5, 'Consensus Checked')], db_index=True, default=1),
        ),
    ]
