# Generated by Django 6.0.4 on 2026-05-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_vacancypromptdecision_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancypromptdecision',
            name='state',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Ready to Execute'), (3, 'ALL_TASKS_EXECUTED'), (4, 'Done'), (5, 'Consensus Checked'), (6, 'Stop Word')], db_index=True, default=1),
        ),
    ]
