# Generated by Django 6.0.4 on 2026-05-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_vacancypromptdecision_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquerypromptlink',
            name='llms',
        ),
        migrations.AddField(
            model_name='prompt',
            name='koef',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='llms',
            field=models.ManyToManyField(related_name='prompts', to='app.executellm'),
        ),
    ]
