# Generated by Django 6.0.4 on 2026-06-23 11:51
import uuid

from django.db import migrations, models


def fill_hash(apps, schema_editor):
    LLMResult = apps.get_model('app', 'LLMResult')
    for result in LLMResult.objects.select_related('vacancy').all():
        text = f"{result.llm}:{result.prompt_id}:{result.vacancy.description.replace(' ', '').lower()}"
        result.task_hash = uuid.uuid3(uuid.NAMESPACE_DNS, text)
        result.save(update_fields=['task_hash'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_searchquerypromptlink_llms_prompt_koef_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmresult',
            name='task_hash',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Task Hash'),
        ),

        migrations.RunPython(code=fill_hash, reverse_code=migrations.RunPython.noop),
    ]
